### PR TITLE
oneplus2-vendor: remove OnePlusCameraService

### PR DESCRIPTION
**Pull request by hbashton**

### CODE REVIEW

**Comment by MSF-Jarvis** [comment]
@xdevs23 I think we need to remove hunter from the GitHub org for a few days till he regains his common sense

**Comment by hbashton** [comment]
Just shhh, it was an accident, I thought I had write access

**Comment by MSF-Jarvis** [comment]
You don't need to kill the camera service and make 3 underp commits in fwb

**Comment by hbashton** [comment]
Simao told me to kill cameraservice

**Comment by MSF-Jarvis** [comment]
Dafuk

**Comment by hbashton** [comment]
Look at previous commits. He said we didn't need it.

**Comment by xdevs23** [comment]
@MSF-Jarvis go sleep for a day

**Pull request closed without merging**
